### ISSUE TITLE
Removing a post (deleting entry) should be handled nicer

### ISSUE THREAD

**Issue by Rexeh** [Firesphere/silverstripe-newsmodule#140]
Currently, removing a post and accessing the old URL, leads to a non-object error... This should be handled gracefully?

Wouldn't be great for SEO right now.

**Comment by Firesphere** [comment]
Have I fixed this yet? I haven't, have I?

Adding another high priority issue to the list.

**Comment by Firesphere** [comment]
I'm probably not going to fix this, since the site is redirected back to the overview with a 404. This issue is only visible in dev-mode, in live-mode it responds with the correct error-code and redirects back.

If the issue exists on a live website, please let me know, because the calls are all correctly captured and redirected, I don't see this as an issue.
